version: "3.7"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/usr/src/app
    networks:
      - app-network
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  backend-data:
  mysql-data:

networks:
  app-network:
    driver: bridge
